In [201]:
import pandas as pd 
import matplotlib.pyplot as plt

In [202]:
from google.colab import files
uploaded = files.upload()

Saving all_patients.csv to all_patients (7).csv

In [203]:
import io
df= pd.read_csv(io.BytesIO(uploaded['all_patients.csv']))
df

,Time,Date,Sample #,Type,Sub,Chan,Num,Aux,Unnamed: 8
0,[23:07:00.004,19/01/1989],1,"""",0,0,0,4 LA LA,NaN
1,[23:07:30.000,19/01/1989],7500,"""",0,0,0,4 LA,NaN
2,[23:08:00.000,19/01/1989],15000,"""",0,0,0,4 LA,NaN
3,[23:08:30.000,19/01/1989],22500,"""",0,0,0,4 L L L,NaN
4,[23:09:00.000,19/01/1989],30000,"""",0,0,0,4 L,NaN
...,...,...,...,...,...,...,...,...,...
10038,[04:00:30.000,04/01/1990],3255000,"""",0,0,0,W,NaN
10039,[04:01:00.000,04/01/1990],3262500,"""",0,0,0,W,NaN
10040,[04:01:30.000,04/01/1990],3270000,"""",0,0,0,W,NaN
10041,[04:02:00.000,04/01/1990],3277500,"""",0,0,0,W,NaN
10042,[04:02:30.000,04/01/1990],3285000,"""",0,0,0,W,NaN

In [204]:
features = df[['Aux']].copy()
features

           Aux
0      4 LA LA
1         4 LA
2         4 LA
3      4 L L L
4          4 L
...        ...
10038        W
10039        W
10040        W
10041        W
10042        W

[10043 rows x 1 columns]

In [205]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.model_selection import learning_curve
from sklearn.model_selection import validation_curve
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

In [206]:
df.describe()

           Sample #      Sub     Chan      Num
count  1.004300e+04  10043.0  10043.0  10043.0
mean   2.460549e+06      0.0      0.0      0.0
std    1.547770e+06      0.0      0.0      0.0
min    1.000000e+00      0.0      0.0      0.0
25%    1.140000e+06      0.0      0.0      0.0
50%    2.287500e+06      0.0      0.0      0.0
75%    3.720000e+06      0.0      0.0      0.0
max    5.842500e+06      0.0      0.0      0.0

In [207]:
df.drop('Unnamed: 8', axis=1, inplace=True)
df.head()

            Time         Date  Sample # Type  Sub  Chan  Num      Aux
0  [23:07:00.004  19/01/1989]         1    "    0     0    0  4 LA LA
1  [23:07:30.000  19/01/1989]      7500    "    0     0    0     4 LA
2  [23:08:00.000  19/01/1989]     15000    "    0     0    0     4 LA
3  [23:08:30.000  19/01/1989]     22500    "    0     0    0  4 L L L
4  [23:09:00.000  19/01/1989]     30000    "    0     0    0      4 L

In [208]:
# split the 'Aux' column into separate columns by space delimiter
features[['state','col_1', 'col_2', 'col_3']] = features['Aux'].str.split(' ', expand=True)

# drop the 'Aux' column
features = features.drop('Aux', axis=1)

# display the resulting DataFrame
print(features)

      state col_1 col_2 col_3
0         4    LA    LA  None
1         4    LA  None  None
2         4    LA  None  None
3         4     L     L     L
4         4     L  None  None
...     ...   ...   ...   ...
10038     W  None  None  None
10039     W  None  None  None
10040     W  None  None  None
10041     W  None  None  None
10042     W  None  None  None

[10043 rows x 4 columns]

In [209]:
features.fillna(0, inplace=True)
features

      state col_1 col_2 col_3
0         4    LA    LA     0
1         4    LA     0     0
2         4    LA     0     0
3         4     L     L     L
4         4     L     0     0
...     ...   ...   ...   ...
10038     W     0     0     0
10039     W     0     0     0
10040     W     0     0     0
10041     W     0     0     0
10042     W     0     0     0

[10043 rows x 4 columns]

In [210]:
new_data={}

In [211]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [212]:
from sklearn.preprocessing import OneHotEncoder

In [213]:
data = features
values = (data)
print(values)

      state col_1 col_2 col_3
0         4    LA    LA     0
1         4    LA     0     0
2         4    LA     0     0
3         4     L     L     L
4         4     L     0     0
...     ...   ...   ...   ...
10038     W     0     0     0
10039     W     0     0     0
10040     W     0     0     0
10041     W     0     0     0
10042     W     0     0     0

[10043 rows x 4 columns]

In [214]:
features.isnull().any()

state    False
col_1    False
col_2    False
col_3    False
dtype: bool

In [215]:
label_encoder = LabelEncoder()

In [216]:
features['col_1'] = features['col_1'].astype(str)

In [217]:
features['col_1'] = label_encoder.fit_transform(features['col_1'])

In [218]:
from sklearn.preprocessing import LabelEncoder
types = features['col_1']
encoder = LabelEncoder()
encoder.fit(types)
labels = encoder.transform(types)

In [219]:
pip install hmmlearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: hmmlearn in /usr/local/lib/python3.9/dist-packages (0.2.8)
Requirement already satisfied: scipy>=0.19 in /usr/local/lib/python3.9/dist-packages (from hmmlearn) (1.10.1)
Requirement already satisfied: numpy>=1.10 in /usr/local/lib/python3.9/dist-packages (from hmmlearn) (1.22.4)
Requirement already satisfied: scikit-learn>=0.16 in /usr/local/lib/python3.9/dist-packages (from hmmlearn) (1.2.2)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from scikit-learn>=0.16->hmmlearn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn>=0.16->hmmlearn) (3.1.0)

In [220]:
from hmmlearn import hmm

In [221]:
features["col_1"] = data["col_1"].diff()

In [224]:
print("Unique states:")
print(states)

Unique states:
[1 0 2]

In [227]:
from hmmlearn import hmm
import numpy as np

np.random.seed(42)
n_samples = 1000
n_features = 3
X = np.random.randn(n_samples, n_features)

# Create a GaussianHMM model with 3 hidden states
model = hmm.GaussianHMM(n_components=3)

# Train the model
model.fit(X)

# Access the learned model parameters
# Transition matrix
print("Learned Transition Matrix:")
print(model.transmat_)

# Emission matrix (means)
print("Learned Emission Means:")
print(model.means_)

# Covariance matrices (variances)
print("Learned Covariance Matrices:")
print(model.covars_)

Learned Transition Matrix:
[[8.36186295e-04 9.56792224e-01 4.23715899e-02]
 [6.25254483e-02 1.06574208e-01 8.30900343e-01]
 [1.27538406e-01 8.36587590e-01 3.58740034e-02]]
Learned Emission Means:
[[ 0.1447679   0.77099567  0.02163622]
 [-0.09129149  0.06814623  0.14206099]
 [ 0.20553164 -0.24627428 -0.05746959]]
Learned Covariance Matrices:
[[[0.7502645  0.         0.        ]
  [0.         1.30421171 0.        ]
  [0.         0.         0.75655246]]

 [[0.99482625 0.         0.        ]
  [0.         0.96419482 0.        ]
  [0.         0.         1.05892435]]

 [[0.86676807 0.         0.        ]
  [0.         0.83419383 0.        ]
  [0.         0.         0.86915994]]]

/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

In [228]:
# Predict the most likely hidden states for a sequence of observations
X_test = np.random.randn(10, n_features)  # Example test data
hidden_states = model.predict(X_test)
print("Predicted Hidden States:")
print(hidden_states)

Predicted Hidden States:
[1 2 0 1 2 1 2 1 2 1]

In [231]:
# Compute the log-likelihood of a sequence of observations
log_likelihood = model.score(X_test)
print("Log-Likelihood of Observations:", log_likelihood)

# Decode the most likely hidden state sequence for a sequence of observations
hidden_states = model.decode(X_test)[1]
print("Decoded Hidden States:")
print(hidden_states)

# Compute the posterior probabilities of hidden states given observations
posterior_probs = model.predict_proba(X_test)
print("Posterior Probabilities of Hidden States:")
print(posterior_probs)

Log-Likelihood of Observations: -46.95853984703774
Decoded Hidden States:
[1 2 0 1 2 1 2 1 2 1]
Posterior Probabilities of Hidden States:
[[1.29764525e-04 9.77463130e-01 2.24071055e-02]
 [3.17937795e-02 1.15215764e-01 8.52990457e-01]
 [3.04556145e-01 5.84852336e-01 1.10591519e-01]
 [5.85807044e-02 4.84384778e-01 4.57034517e-01]
 [7.04036511e-02 4.43560792e-01 4.86035557e-01]
 [1.51093931e-02 7.58749014e-01 2.26141593e-01]
 [7.53823687e-02 2.29635127e-01 6.94982505e-01]
 [7.72033298e-02 7.92329551e-01 1.30467119e-01]
 [4.36305306e-02 1.87748698e-01 7.68620771e-01]
 [1.68049997e-01 6.99978226e-01 1.31971777e-01]]

In [232]:
X_generated, hidden_states_generated = model.sample(10)
print("Generated Observations:")
print(X_generated)

print("Generated Hidden States:")
print(hidden_states_generated)

Generated Observations:
[[ 0.4796162   0.51060914 -1.18863403]
 [-0.09967331 -0.55543507 -1.80067596]
 [ 0.15953074 -0.12261328  0.54233585]
 [-1.22102667  0.40628094 -0.63567907]
 [-0.12779508 -0.37359161  0.40047716]
 [-0.30562313  1.61569502  0.09424812]
 [-0.50171877 -0.01947584  0.21685219]
 [ 0.52615465 -0.31419825 -0.09249624]
 [-1.1098089   0.53306449  1.12124424]
 [-0.38120423 -0.18240493 -0.30698803]]
Generated Hidden States:
[1 2 1 1 2 0 1 2 1 2]

In [255]:
import numpy as np
from hmmlearn import hmm

np.random.seed(0)
n_samples = 1000
obs_len = 10
n_states = 3
X = np.random.randn(n_samples, obs_len)

# Define the HMM model
model = hmm.GaussianHMM(n_components=n_states, n_iter=100, tol=0.01)

# Fit the model using the EM algorithm
model.fit(X)

# Print the learned parameters
print("Learned Transition Matrix:")
print(model.transmat_)
print("Learned Means of Gaussian Emission Distribution:")
print(model.means_)
print("Learned Covariance Matrices of Gaussian Emission Distribution:")
print(model.covars_)

/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

Learned Transition Matrix:
[[0.85866126 0.1388229  0.00251584]
 [0.13613286 0.22129921 0.64256793]
 [0.39730229 0.44394904 0.15874867]]
Learned Means of Gaussian Emission Distribution:
[[-0.04800428  0.14991428 -0.02841996 -0.02419125  0.01745571 -0.01497119
  -0.03015443 -0.14480607  0.09465391 -0.01778329]
 [-0.16822716 -0.19962814 -0.20301346  0.06001819  0.05095834 -0.34487761
   0.08559232  0.09396867 -0.12185424  0.56150147]
 [ 0.29072918 -0.21241069  0.13543281 -0.32139339 -0.35069533  0.20779897
  -0.04591262  0.16799049 -0.32883898 -0.28393487]]
Learned Covariance Matrices of Gaussian Emission Distribution:
[[[0.90507354 0.         0.         0.         0.         0.
   0.         0.         0.         0.        ]
  [0.         0.86835683 0.         0.         0.         0.
   0.         0.         0.         0.        ]
  [0.         0.         0.90323008 0.         0.         0.
   0.         0.         0.         0.        ]
  [0.         0.         0.         0.88653544 0.         0.
   0.         0.         0.         0.        ]
  [0.         0.         0.         0.         1.10409909 0.
   0.         0.         0.         0.        ]
  [0.         0.         0.         0.         0.         1.11756645
   0.         0.         0.         0.        ]
  [0.         0.         0.         0.         0.         0.
   0.84969171 0.         0.         0.        ]
  [0.         0.         0.         0.         0.         0.
   0.         1.08953112 0.         0.        ]
  [0.         0.         0.         0.         0.         0.
   0.         0.         1.12627261 0.        ]
  [0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.86042722]]

 [[1.04536806 0.         0.         0.         0.         0.
   0.         0.         0.         0.        ]
  [0.         1.32262616 0.         0.         0.         0.
   0.         0.         0.         0.        ]
  [0.         0.         1.28788727 0.         0.         0.
   0.         0.         0.         0.        ]
  [0.         0.         0.         1.0895114  0.         0.
   0.         0.         0.         0.        ]
  [0.         0.         0.         0.         0.79061155 0.
   0.         0.         0.         0.        ]
  [0.         0.         0.         0.         0.         0.65943446
   0.         0.         0.         0.        ]
  [0.         0.         0.         0.         0.         0.
   0.90881437 0.         0.         0.        ]
  [0.         0.         0.         0.         0.         0.
   0.         1.0266514  0.         0.        ]
  [0.         0.         0.         0.         0.         0.
   0.         0.         1.03715733 0.        ]
  [0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.7174896 ]]

 [[1.40725013 0.         0.         0.         0.         0.
   0.         0.         0.         0.        ]
  [0.         0.70529957 0.         0.         0.         0.
   0.         0.         0.         0.        ]
  [0.         0.         0.94415731 0.         0.         0.
   0.         0.         0.         0.        ]
  [0.         0.         0.         0.93070563 0.         0.
   0.         0.         0.         0.        ]
  [0.         0.         0.         0.         0.6152934  0.
   0.         0.         0.         0.        ]
  [0.         0.         0.         0.         0.         0.65047201
   0.         0.         0.         0.        ]
  [0.         0.         0.         0.         0.         0.
   1.04917273 0.         0.         0.        ]
  [0.         0.         0.         0.         0.         0.
   0.         0.60060579 0.         0.        ]
  [0.         0.         0.         0.         0.         0.
   0.         0.         0.346866   0.        ]
  [0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.89892028]]]

In [253]:
logprob, state_seq = model.decode(X, algorithm='viterbi')
state_seq

array([0, 2, 1, 1, 0, 2, 0, 2, 1, 1, 1, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0,
       2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 1, 1, 0, 0, 2, 0, 2,
       1, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 1, 1, 1, 0, 2, 0, 2, 0, 0, 2, 1,
       0, 0, 2, 0, 2, 0, 0, 2, 1, 1, 0, 2, 0, 0, 2, 1, 1, 1, 0, 2, 0, 2,
       0, 2, 1, 1, 1, 0, 2, 0, 2, 0, 2, 0])

In [256]:
import numpy as np
from hmmlearn import hmm
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

model = hmm.GaussianHMM(n_components=3)  
X = np.random.randn(100, 3) 
model.fit(X)

obs_seq, _ = model.sample(6)  

hidden_states = model.predict(obs_seq)

ground_truth_labels = np.array([0, 1, 2, 1, 0, 2]) 

# Calculate accuracy
accuracy = accuracy_score(ground_truth_labels, hidden_states)

# Calculate precision
precision = precision_score(ground_truth_labels, hidden_states, average='weighted')

# Calculate recall
recall = recall_score(ground_truth_labels, hidden_states, average='weighted')

# Calculate F1-score
f1_score = f1_score(ground_truth_labels, hidden_states, average='weighted')

# Print the calculated metrics
print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1-score: ", f1_score)

Accuracy:  0.5
Precision:  0.3333333333333333
Recall:  0.5
F1-score:  0.4000000000000001

/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))